Copyright by Arjun Sarkar Research Group Applied Systems Biology - Head: Prof. Dr. Marc Thilo Figge https://www.leibniz-hki.de/en/applied-systems-biology.html HKI-Center for Systems Biology of Infection Leibniz Institute for Natural Product Research and Infection Biology - Hans Knöll Insitute (HKI) Adolf-Reichwein-Straße 23, 07745 Jena, Germany

In [1]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import numpy as np
import seaborn as sns
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import cv2 as cv
import shutil

In [2]:
df = pd.read_csv('Labels.csv')
df.head()

Video_Num Inefction_type  Patient  Patient_id
0          1             ca        1    20180220
1          2             cg        1    20180220
2          3           mock        1    20180220
3          4             ca        2    20180315
4          5             cg        2    20180315

In [3]:
video_type = df[df['Inefction_type'] == 'cg']
video_cg = video_type['Video_Num'].tolist()
video_cg = np.array(video_cg)
video_cg

array([ 2,  5, 14, 19, 22, 25, 28, 31, 34])

In [4]:
video_type = df[df['Inefction_type'] == 'ca']
video_ca = video_type['Video_Num'].tolist()
video_ca = np.array(video_ca)
video_ca

array([ 1,  4, 13, 18, 21, 24, 27, 30, 33])

In [5]:
video_type = df[df['Inefction_type'] == 'mock']
video_mock = video_type['Video_Num'].tolist()
video_mock = np.array(video_mock)
video_mock

array([ 3,  6, 15, 20, 23, 26, 29, 32, 35])

In [6]:
path = '/asbdata/Arjun/Bloodi/Split_40_Frames/'

In [7]:
data = []

for folders in os.listdir(path):
    
    folder = np.int(folders)
    
    if folder in video_cg:
        label = 'cg'
        classes = 1
            
    if folder in video_ca:
        label = 'ca'
        classes = 0
            
    if folder in video_mock:
        label = 'mock'
        classes = 2

    for videos in os.listdir(os.path.join(path,folders)):
        
        data.append([np.int32(folders),videos,label,classes])
        
new_df = pd.DataFrame(data,columns=['folder_num','video_name','labels','class_label'])
new_df       

/tmp/ipykernel_3674090/1875435944.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  folder = np.int(folders)


folder_num          video_name labels  class_label
0              19    19_57_57_184.avi     cg            1
1              19  19_158_158_289.avi     cg            1
2              19    19_49_49_157.avi     cg            1
3              19     19_10_10_22.avi     cg            1
4              19  19_241_241_351.avi     cg            1
...           ...                 ...    ...          ...
10669          31  31_739_739_442.avi     cg            1
10670          31  31_678_678_430.avi     cg            1
10671          31  31_322_322_267.avi     cg            1
10672          31  31_592_592_388.avi     cg            1
10673          31  31_617_617_399.avi     cg            1

[10674 rows x 4 columns]

In [8]:
new_df.to_csv('Video_list_split_cells.csv',index = False)

In [9]:
df = pd.read_csv('Video_list_split_cells.csv')
df

folder_num          video_name labels  class_label
0              19    19_57_57_184.avi     cg            1
1              19  19_158_158_289.avi     cg            1
2              19    19_49_49_157.avi     cg            1
3              19     19_10_10_22.avi     cg            1
4              19  19_241_241_351.avi     cg            1
...           ...                 ...    ...          ...
10669          31  31_739_739_442.avi     cg            1
10670          31  31_678_678_430.avi     cg            1
10671          31  31_322_322_267.avi     cg            1
10672          31  31_592_592_388.avi     cg            1
10673          31  31_617_617_399.avi     cg            1

[10674 rows x 4 columns]

In [10]:
os.mkdir('/asbdata/Arjun/Bloodi/all_split_videos/')

for folders in os.listdir(path):
    
    for videos in os.listdir(os.path.join(path,folders)):
        
        dest_dir = '/asbdata/Arjun/Bloodi/all_split_videos/'
        shutil.copy(path+str(folders)+'/'+videos, dest_dir)

In [11]:
os.mkdir('/asbdata/Arjun/Bloodi/Split_numpy')
os.mkdir('/asbdata/Arjun/Bloodi/Split_numpy/videos')
os.mkdir('/asbdata/Arjun/Bloodi/Split_numpy/labels')